### ISSUE TITLE
About us page goes nowhere

### ISSUE THREAD

**Issue by alexjamesmalcolm** [NAPOSCA/pantryplus#113]
If you click on the link in the footer it doesn't lead to any page.

**Comment by JDSalisbury** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [About us page goes nowhere](https://trello.com/c/8PSfhiUu/131-about-us-page-goes-nowhere)

**Comment by theoccasionalist** [comment]
Where do we want the about us page to go?  Do we want to create a new page for this?

**Comment by JDSalisbury** [comment]
A new page, covered in cats. and just a simple bio of each of us i think. with our github pages linked. kinda meet the team.

**Comment by JDSalisbury** [comment]
[https://blog.hubspot.com/marketing/remarkable-about-us-page-examples](url)

**Comment by theoccasionalist** [comment]
Jeff, that was a joke, right?  

I hope so.  It was funny.
