### ISSUE TITLE
Entering 'Other' ZipCode doesn't redirect the user to an error page

### ISSUE THREAD

**Issue by alexjamesmalcolm** [NAPOSCA/pantryplus#83]
The other zip code should send the user to a page that lets them know that they aren't in a zip code that's supported by the food pantry. Currently, it just lets the user pass to the shopping view.

**Comment by alexjamesmalcolm** [comment]
Should be swapped with an input, and if they enter the wrong zip code, redirect to their food pantry.

**Comment by Dean110** [comment]
I have a branch that will fix the initial comment to this issue.  The second comment seems like a feature for a network of food pantries that doesn't exist yet.  I'll be submitting the PR for the first comment however.  The second comment, changing the form element to an input and having it redirect seems a bit future feature.
I could add a 'checker' class to check the zipcode against a whitelist of zipcodes before passing onto the order form.  Before I do that, maybe we open another issue?

**Comment by alexjamesmalcolm** [comment]
That sounds like a great idea! I'll open a feature issue for the second comment.

**Comment by theoccasionalist** [comment]
Is this still an issue?

**Comment by alexjamesmalcolm** [comment]
This was fixed by #146
